config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
     sessions: 'users/sessions', registrations: 'users/registrations'
  }
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard", as: :dashboard
  get "profile/:id", to: "pages#profile", as: :profile
  get "users", to: "pages#users"
  get "map", to: "foodplaces#map"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foodplaces do
    member do
      patch :favorite
    end
    resources :reviews, only: :create
  end

  # resources :reviews
  get "map", to: "foodplaces#map"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
  # not sure about the routes
  get "follow", to: "followers#follow"
  post '/users/:id/follow', to: "followers#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "followers#unfollow", as: "unfollow_user"
end

app/models/foodplace.rb
class Foodplace < ApplicationRecord
  acts_as_favoritable
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :name, :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def average_rating
    all_ratings = reviews.pluck(:rating).compact
    (all_ratings.sum / all_ratings.count).round(1) unless all_ratings.count.zero?
  end
end

app/controllers/foodplaces_controller.rb
class FoodplacesController < ApplicationController
  before_action :set_foodplace, only: %i[show favorite]

  def index
    if params[:query].present?
      @foodplaces = Foodplace.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @foodplaces = Foodplace.order(google_rating: :desc)
      # @markers = @foodplaces.geocoded.map do |foodplace|
      # {
      #   lat: foodplace.latitude,
      #   lng: foodplace.longitude,
      #   info_window: render_to_string(partial: "info_window", locals: { foodplace: foodplace })
      # }
      # end
    end
  end

  def show
    @review = Review.new
    @markers = [
      {
        lat: @foodplace.latitude,
        lng: @foodplace.longitude,
        info_window: render_to_string(partial: "info_window", locals: { foodplace: @foodplace }),
        image_url: helpers.asset_url("restaurant.png")

      }
    ]
  end

  def map
    @foodplaces = Foodplace.all
    @markers = @foodplaces.geocoded.map do |foodplace|
      {
        lat: foodplace.latitude,
        lng: foodplace.longitude,
        info_window: render_to_string(partial: "info_window", locals: { foodplace: foodplace }),
        image_url: helpers.asset_url("restaurant.png")

      }
    end
  end

  def favorite
    current_user.favorite(@foodplace, scope: params[:scope])
  end

  # def follow
  #   current_user.favorite(@foodplace, scope: params[:scope])
  # end

  # def bookmark
  #   current_user.favorite(@foodplace, scope: params[:scope])
  # end

  private

  def set_foodplace
    @foodplace = Foodplace.find(params[:id])
  end

  def foodplace_params
    params.require(:foodplace).permit(:name, :address, :phone_number, :category, :cuisine, :website, :google_rating, :opening_times, :photo)
    # when attaching a photo to foodplace
    # params.require(:foodplace).permit(:name, :photo)
  end
end

app/views/foodplaces/_info_window.html.erb
<%= link_to foodplace_path(foodplace) do %>
  <div class="card-product border shadow rounded bg-color">

    <% if foodplace.photo.present? %>
      <%= cl_image_tag foodplace.photo.key %>
    <% else %>
      <img src="https://imgflip.com/s/meme/Grandma-Finds-The-Internet.jpg" />
    <% end %>

    <div class="card-product-infos d-flex flex-column">
      <p><%= foodplace.name %></p>
      <p><%= foodplace.address %></p>
    </div>

  </div>

<% end %>

app/views/foodplaces/_review.html.erb
<div class="container review-card" data>
  <div class="stars-review">
    <% review.rating.to_i.times do %>
      <i class="fa-solid fa-star my-3 fa-2x"></i>
    <% end %>
    <% (5 - review.rating.to_i).times do %>
      <i class="fa-regular fa-star my-3 fa-2x"></i>
    <% end %>
    <% if review.highlight.present? %>
      <p><strong><%= review.highlight %></strong></p>
    <% end %>
    <% if review.comment.present? %>

      <p><%= review.comment %></p>
    <% end %>
    <div class="d-flex my-2 justify-content-between">
      <p class="fw-lighter"><%= current_user.nickname %></p>
      <p class="fst-italic"><%= review.created_at.strftime("%B %d, %Y") %></p>
    </div>
  </div>
</div>

app/views/foodplaces/_user_rating.html.erb
<div class="ratings-card" data-insert-in-list-target="status">

  <% if foodplace.average_rating  %>
    <h2>User rating <%= foodplace.average_rating %></h2>
  <% else %>
    <h2>No user rating so far</h2>
  <% end %>
  <h4>Google rating <%= foodplace.google_rating %></h4>
</div>

app/views/foodplaces/index.html.erb
<!--<div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2>Title here</h2>
      <p>Short description here!</p>
    </div>
    <h2 class="card-trip-pricing">£99.99</h2>
    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
  </div>
</div>
-->

<div class="container">
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane my-5 fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
      <%= form_with url: foodplaces_path, method: :get, class: "d-flex"  do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "search for a foodplace"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>

  <div class="card-wrap">
    <% @foodplaces.each do |foodplace| %>
      <div class="card-thumbnail">
        <div class="card-single">
          <%= link_to foodplace_path(foodplace), class: "w-100" do %>
            <div class="card-image">
              <% if foodplace.photo.present? %>
                <%= cl_image_tag foodplace.photo.key%>
              <% else %>
                <img src="https://imgflip.com/s/meme/Grandma-Finds-The-Internet.jpg" />
              <% end %>
            </div>
            <div class="d-flex circle-wrapper mt-2 mb-1">
              <% x = foodplace.google_rating %>
              <% ((((x * 2.0).round / 2.0)) - ((x * 2.0).round / 2.0) % 1).to_i.times do  %>
                <div class="circle-full"></div>
              <% end %>
              <% empty_circle = 0 %>
              <%if((((x * 2.0).round / 2.0) % 1) < 0.5) %>
              <% half_circle = 0 %>
              <% else %>
              <% half_circle = 1 %>
              <% end %>
              <% half_circle.times do %>
                <div class="circle-half"></div>
                <div class="circle-empty"></div>
              <% end %>
              <% (5 - (((x * 2.0).round / 2.0)) - ((x * 2.0).round / 2.0) % 1).to_i.times do %>
                <div class="circle"></div>
              <% end %>
            </div>
            <div class="card-info-wrapper">
              <h4><%= foodplace.name %></h4>
              <p><%= foodplace.address %></p>
              <% if foodplace.opening_times.present? %>
              <p><%= foodplace.opening_times %></p>
              <% end %>
            </div>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/foodplaces/map.html.erb
 <div class="mt-2 map_styiling">
    <!--add map -->
    <div id="map" style="width: 100%; height: 83vh;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    @markers = @foodplaces.map do |foodplace|
    {
      lat: foodplace.latitude,
      lng: foodplace.longitude,
      info_window: render_to_string(partial: "info_window", locals: {foodplace: foodplace}),
      image_url: ""https://imgflip.com/s/meme/Grandma-Finds-The-Internet.jpg""
    }
  end
    <!------------>
  </div>

app/views/foodplaces/show.html.erb
<div class="container"  data-controller="insert-in-list" data-insert-in-list-position-value="beforeend">
  <% if @foodplace.photo.attached?%>
    <%= cl_image_tag @foodplace.photo.key, height: 200, width: 150, crop: :fill, class: "show-img" %>
  <% else %>
    <img src="https://imgflip.com/s/meme/Grandma-Finds-The-Internet.jpg" />
  <% end %>
  <div>
    <div class="info">
      <h2 class="mb-3"><%= @foodplace.name %></h2>
      <%= render "foodplaces/user_rating", foodplace: @foodplace %>
    </div>
    <!-- Button trigger modal -->
    <hr>
    <div class="d-flex justify-content-between" data-controller="buttonchange">
      <%# <button type="button" class="btn  show-btn fa-3x my-2" data-bs-toggle="modal" data-bs-target="#review">
        <i class="fa-solid fa-star"></i>
      </button> %>
      <div>
        <%= link_to favorite_foodplace_path(@foodplace, scope: :favorite), data: { turbo_method: :patch , action: "click->buttonchange#changeHeart" } do %>
          <i data-buttonchange-target="heart" class="fa-regular fa-heart show-btn fa-3x my-2"></i>
        <% end %>
      </div>
      <div>
        <%= link_to favorite_foodplace_path(@foodplace, scope: :saved), data: { turbo_method: :patch, action: "click->buttonchange#changeBookmark" } do %>
          <i data-buttonchange-target="bookmark" class="fa-regular fa-bookmark show-btn fa-3x my-2"></i>
        <% end %>
      </div>
      <div>
        <%= link_to favorite_foodplace_path(@foodplace, scope: :visited), data: { turbo_method: :patch, action: "click->buttonchange#changeVisited"} do %>
          <i data-buttonchange-target="visited" class="fa-regular fa-circle-check show-btn fa-3x my-2 "></i>
        <% end %>
      </div>
    </div>
    <hr>
  </div>

<%# <button class="button-57" role="button"><span class="fa-regular fa-circle-check show-btn fa-3x my-2"></span><span>favorited</span></button> %>

<%# SHOW-TABS---------------------------------------------------------------------------------------------------- %>
  <div class="show-tabs my-2">
    <div class="w-100">
      <ul class="nav nav-pills mb-2 justify-content-between" id="pills-tab" role="tablist">
        <li class="nav-item pe-3 flex-fill w-50" role="presentation">
          <button class="nav-link active w-100" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Info</button>
        </li>
        <li class="nav-item flex-fill w-50" role="presentation">
          <button class="nav-link w-100" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Reviews</button>
        </li>
      </ul>
    </div>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <hr>
      <!--add map -->
      <div id="map" class="mb-5"style="width: 100%; height: 200px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
        <h4><%= @foodplace.address %></h4>
        <hr>
        <h4>Category: <%= @foodplace.category %></h4>
        <hr>
        <h4>Cuisine:  <%= @foodplace.cuisine %></h4>
      </div>
      <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <div class="reviews" >
          <div data-insert-in-list-target="items">
            <% if @foodplace.reviews.blank? %>
              Be the first to leave a review for "<%= @foodplace.name %>"
            <% else %>
                <h2>
                  <%= pluralize @foodplace.reviews.size, "review" %>
                </h2>
                <% @foodplace.reviews.each do |review| %>
                  <%= render "review", review: review, current_user: current_user %>
                <% end %>
            <% end %>
          </div>
          <button type="button" class="btn w-100  btn-primary" data-bs-toggle="modal" data-bs-target="#review">
            Leave a review
          </button>
          <!-- Modal -->
          <div class="modal fade" id="review" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Please add a review</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <div >
                      <%= render "reviews/form", foodplace: @foodplace, review: @review %>
                      <button type="button" data-insert-in-list-target="close" class="btn btn-secondary d-none" data-bs-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>