config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
     sessions: 'users/sessions', registrations: 'users/registrations'
  }
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard", as: :dashboard
  get "profile/:id", to: "pages#profile", as: :profile
  get "users", to: "pages#users"
  get "map", to: "foodplaces#map"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foodplaces do
    member do
      patch :favorite
    end
    resources :reviews, only: :create
  end

  # resources :reviews
  get "map", to: "foodplaces#map"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
  # not sure about the routes
  get "follow", to: "followers#follow"
  post '/users/:id/follow', to: "followers#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "followers#unfollow", as: "unfollow_user"
end

app/views/pages/home.html.erb
<div class="container mt-2">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Foodplaces</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Users</button>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
      <%= form_with url: foodplaces_path, method: :get, class: "d-flex"  do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "search for a foodplace"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
      <%= form_with url: users_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "search for a user"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<%= render "shared/carousel", foodplaces: @top_rated_foodplaces %>

app/views/pages/profile.html.erb
<div class="d-flex flex-column">

  <div class="d-flex flex-column align-items-center">
    <% if @user.photo.attached? %>
      <%= cl_image_tag @user.photo.key, class: "profile_pic"%>
    <% else %>
        <img src="https://imgflip.com/s/meme/Grandma-Finds-The-Internet.jpg" class = "profile_pic"/>
    <% end %>

    <div class="d-flex justify-content-center my-2">
      <%= @user.first_name %>
      <%= @user.last_name %>
    </div>
    <% if 	current_user == @user %>
      <div class="d-flex justify-content-between align-items-center">
        <%= link_to "Edit", edit_user_registration_path, class: 'small text-secondary me-2' %>
        <%= link_to 'Delete account', user_registration_path, confirm: 'Are you sure you want to destroy your account?', method: :delete, class: "small text-secondary" %>
      </div>
    <% end %>
  </div>

  <div class="d-flex flex-column mx-4 my-2 p-3 border shadow rounded">
    <p><span class="small text-secondary">First name: </span> <%= @user.first_name %></p>
    <p><span class="small text-secondary">Last name: </span> <%= @user.last_name %></p>
    <p><span class="small text-secondary">Email-address: </span> <%= @user.email %></p>
  </div>

  <div class="d-flex flex-column mx-4 my-2 p-3 border shadow rounded">
    <p><span class="small text-secondary">Nickname: </span> <%= @user.nickname %></p>
    <p><span class="small text-secondary">Diet: </span> <%= @user.diet %></p>
    <p><span class="small text-secondary">Likes: </span> <%= @user.likes %></p>
    <p><span class="small text-secondary">Dislikes: </span> <%= @user.dislikes %></p>
    <p><span class="small text-secondary">Allergies: </span> <%= @user.allergies %></p>
    <p><span class="small text-secondary">Bio: </span> <%= @user.bio %></p>
  </div>

</div>

<%# ...........................................Tab Bar................................................... %>

<div class="mx-4 my-2">
 <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel">Following</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
<div class="modal-body">
      <%@followers.each do |follower| %>
    <%= link_to profile_path(follower.followable_id) do %>
    <div class="container mt-3 new-card">
            <% user = User.find(follower.followable_id) %>
            <p style="color: white"><%= user.first_name %></p>
        <% end %>
    </div>
  <% end %>
</div>
      <div class="modal-footer">
        <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" data-bs-dismiss="modal">Open followers</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel2">Followers</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-body">

          <%@followers.each do |follower| %>
    <%= link_to profile_path(follower.followable_id) do %>
    <div class="container mt-3 new-card", style="color: white">
            <% user = User.find(follower.followable_id) %>
            <p style="color: white"><%= user.first_name %></p>
        <% end %>
    </div>
  <% end %>

      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal" data-bs-dismiss="modal">Back to followings</button>
      </div>
    </div>
  </div>
</div>
<a class="btn btn-primary" data-bs-toggle="modal" href="#exampleModalToggle" role="button" style="width:100%">Connections</a>

  <ul class="nav nav-pills justify-content-between mb-3 border shadow rounded" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button"  aria-controls="pills-home" aria-selected="true">My Favorites</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Saved</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Visited</button>
    </li>
  </ul>
  <div class="tab-content " id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <div>
        <% @favorites.each do |f| %>
          <%= link_to foodplace_path(f.favoritable_id) do %>
            <div class="card-product border shadow rounded">
              <% if Foodplace.find(f.favoritable_id).photo.attached? %>
                <%= cl_image_tag Foodplace.find(f.favoritable_id).photo.key%>
              <% else %>
                <img src="https://imgflip.com/s/meme/Grandma-Finds-The-Internet.jpg"/>
              <% end %>
              <div class="card-product-infos d-flex flex-column">
                <p><%= Foodplace.find(f.favoritable_id).name %></p>
                <p><%= Foodplace.find(f.favoritable_id).address %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
      <div>
        <% @saves.each do |f| %>
          <%= link_to foodplace_path(f.favoritable_id) do %>
            <div class="card-product border shadow rounded">
              <% if Foodplace.find(f.favoritable_id).photo.attached? %>
                <%= cl_image_tag Foodplace.find(f.favoritable_id).photo.key%>
              <% else %>
                <img src="https://imgflip.com/s/meme/Grandma-Finds-The-Internet.jpg"/>
              <% end %>
              <div class="card-product-infos d-flex flex-column">
                <p><%= Foodplace.find(f.favoritable_id).name %></p>
                <p><%= Foodplace.find(f.favoritable_id).address %></p>
              </div>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
      <div>
        <% @visits.each do |f| %>
          <%= link_to foodplace_path (f.favoritable_id) do %>
            <div class="card-product border shadow rounded">
              <% if Foodplace.find(f.favoritable_id).photo.attached? %>
                <%= cl_image_tag Foodplace.find(f.favoritable_id).photo.key %>
              <% else %>
                <img src="https://imgflip.com/s/meme/Grandma-Finds-The-Internet.jpg" />
              <% end %>
              <div class="card-product-infos d-flex flex-column">
                <p><%= Foodplace.find(f.favoritable_id).name %></p>
                <p><%= Foodplace.find(f.favoritable_id).address %></p>
              </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
    <!-- Button trigger modal -->
  <!-- Modal -->
</div>

app/views/pages/users.html.erb
<div class="container mt-5">
  <%= form_with url: users_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "search for a user"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  <h1 class="users-title">ALL FOODIES</h1>
  <% @users.each do |user| %>
    <% unless current_user == user %>
      <div class="new-card">
        <%= link_to profile_path(user), class: 'd-flex align-items-center'  do %>
          <div class="avatar-large pe-3">
            <%= cl_image_tag user.photo.key if user.photo.attached?%>
          </div>
          <h2 class="user-name-text"><%= user.first_name%></h2>
        <% end %>
        <% if current_user.following?(user) %>
          <%= link_to unfollow_user_path(current_user, user: user), data: { turbo_method: :post } do %>
            <i class="fa-solid fa-user-minus fa-2x"></i>
          <% end %>
        <% else %>
          <%= link_to follow_user_path(current_user, user: user) , data: { turbo_method: :post } do %>

            <i class="fa-solid fa-user-plus fa-2x"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>